<?php
/**
 * @category    Herve
 * @package     Herve_Fluidity
 * @copyright   Copyright (c) 2013 Hervé Guétin (http://www.herveguetin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_helper = Mage::helper('customer') ?>
<li>
    <a href="<?php echo $_helper->getAccountUrl() ?>" class="right tiny button split">My Account<span data-dropdown="customer_top_links"></span></a>
    <ul id="customer_top_links" class="f-dropdown" data-dropdown-content>
        <?php if($_helper->isLoggedIn()): ?>
            <li><a href="<?php echo $_helper->getLogoutUrl() ?>"><?php echo $this->__('Log Out') ?></a></li>
        <?php else: ?>
            <li><a href="<?php echo $_helper->getLoginUrl() ?>"><?php echo $this->__('Log In') ?></a></li>
            <li><a href="<?php echo $_helper->getRegisterUrl() ?>"><?php echo $this->__('Create an Account') ?></a></li>
        <?php endif ?>
    </ul>
</li>