<?php
/**
 * @category    Herve
 * @package     Herve_Fluidity
 * @copyright   Copyright (c) 2013 Hervé Guétin (http://www.herveguetin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('vendor/jquery.js') ?>"></script>
<script>jQuery.noConflict()</script>

<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation.min.js') ?>"></script>

<!--
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.alerts.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.clearing.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.cookie.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.dropdown.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.forms.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.joyride.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.magellan.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.orbit.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.reveal.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.section.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.tooltips.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.topbar.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.interchange.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.placeholder.js') ?>"></script>
<script src="<?php echo Mage::helper('fluidity')->getFoundationJs('foundation/foundation.abide.js') ?>"></script>
-->

<script>
    jQuery(document).foundation();
</script>